# Generated by Django 4.1.3 on 2022-12-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='cartegories',
            new_name='categories',
        ),
    ]
